### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by notshi** [IATI/validator-services#117]
Hello,

Wasn't sure if this is the right place to post this issue but it was the link that we found via the [API page](https://developer.iatistandard.org/api-details#api=iati-validator-v2&operation=get-pub-get-report).

We are subscribed to the Full Access option of the Validator API and are now trying to use it.
It looks like we've hit a rate limit so are facing errors.

We want to get existing reports for each file from the Registry; ie.
``` https://api.iatistandard.org/validator/report[?id][&url][&hash] ```

This adds up to about 13,257 calls.
It worked for the first couple of hundred but we are now blocked.

If the rate limit is 100/min, which it looks like it might be, then it will take us 2 hours to download 13k files. Is this expected?

Is there a way of batching these calls so we don't have to make 13k separate calls?

**Comment by alexlydiate** [comment]
Hi @notshi - we're discussing this, and we'll drop you a line shortly with, I think, a good option.

**Comment by sylvanr** [comment]
Hey guys,

Any updates on this? 

Noticed [get-stats-all](https://github.com/IATI/validator-services/blob/develop/pub-get-stats-all/index.js) being worked on, so hopeful for a yes!

**Comment by alexlydiate** [comment]
The global rate limits will remain as-is for the present - if a specific use case requires a greater limit, please contact support@iatistandard.org and it can be considered on its merit.

**Comment by matmaxgeds** [comment]
@alexlydiate can I confirm that if the limit is raised, it will be done so for all users i.e. there will not be some users with faster access than other users?

**Comment by siemvaessen** [comment]
When is what usecase considered on its merit? Where can we find the Global Rate Limit documented? And any reason to not increase the limit for all users, the objective is for IATI data to be re-used?

**Comment by matmaxgeds** [comment]
1 month bump - any thoughts on these questions much appreciated :)
